### ISSUE TITLE
Create a denote note including the citekey and bib keyword in one step.

### ISSUE THREAD

**Issue by MirkoHernandez** [pprevos/citar-denote#17]
I'm trying to improve my usage of citar in  a denote note-taking workflow.  This packages seems like it could provide all the necessary elements but  I'm not  understanding how to create a regular denote file with the additional citekey included in the front matter.  Is this supposed to be done in a two step process? 

- create a regular denote note.
- use the `citar-denote-add-citekey` command.

If that where the case, could you provide some programmatic examples in the documentation of how to make use of the citar-denote template?. This would  seem really useful for programmatically creating notes with the proper citekeys.

**Comment by ColibanWater** [comment]
Hi Mirko, 

Use the `citar-create-note` function. It has a range of options fully described in the README file on this repository.

Alternatively, you can do it from within the Citar completion menu by selecting an entry and select "Crreate Notes".

Hope that helps.

P:)

**Comment by pprevos** [comment]
Hi Mirko,

Use the citar-create-note function. It has a range of options fully described in the README file on this repository.

Alternatively, you can do it from within the Citar completion menu by selecting an entry and select "Crreate Notes".

There are various options for a default note title;
- Title
- Author (Year)
- Full citation
- Citekey

Would it be best to use the bib keyword as a file tag in Denote rather than in the title?

Hope that helps.

P:)

**Comment by MirkoHernandez** [comment]
Using  `citar-create-note `  just creates a single file (named after the citekey)  in the `citar-notes-paths`  directory  and then opens that buffer.  My understanding is that this is how regular citar works, all the bibliographic notes are included in this single file. Maybe I misread something but the README seems to describe how this single file is created.

I would like to have the bibliographic notes to be separate denote files. I can convert older notes using the `citar-denote-add-citekey`  (which seems to be working great by the way) but I still don't know how to create new bibliographic notes from scratch.

**Comment by pprevos** [comment]
Notes are created in the `denote-directory` because the note is created with Denote. There is a many-to-many relationship between notes and bibliographic items to give the user freedom to organise notes. The Denote identifier ensures that each note has a unique file name.

Citar is only used to access the bibliographic information. In my setup `citar-notes-path` is `nil` (I will clarify this in the documentation soon).

**Comment by MirkoHernandez** [comment]
Thanks for the clarification, I did not realize that I had to enable the `citar-denote-mode`,  now the function creates the note, otherwise it has the normal citar behavior (maybe an alias` citar-denote-create-note` or an additional function could be used for calling the function directly) .

I' think that I get now how citar-denote works: There is no single file containing the bibliographic notes (unlike citar), and  the bib keyword is used for performance reasons (for collecting the references). This seems like a cool aproach, thanks!.

**Comment by pprevos** [comment]
Excellent. 

The minor mode should create these aliases. The package configures `citar-notes-source` variable to make notes happen. I have updated the manual to prevent future confusion.

**Comment by pprevos** [comment]
Hi @MirkoHernandez , based on your comment about keywords, the latest version now has an option to extract keywords from the bib file and use these as Denote keywords.
